version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000  # Example port mapping for React Native development
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "while sleep 1000; do :; done"
